function updateuiParamsGA
% Обновление интерфейса ScheduleBuilder
% в секции "Параметры ГА"

global paramsGA;
set( findobj( 'Tag','editCHCount' ), ...
     'String',num2str( paramsGA.nCH ) );
set( findobj( 'Tag','editMutationsPerc' ), ...
     'String',num2str( paramsGA.pMutations ) );
set( findobj( 'Tag','listboxCrossoverType' ), ...
     'Value',paramsGA.crossoverType );
set( findobj( 'Tag','listboxMutationType' ), ...
     'Value',paramsGA.mutationType );
set( findobj( 'Tag','editIterationsNumber' ), ...
     'String',num2str( paramsGA.iterations ) );
